base_url = "https://eodus.github.io"
title = "Sasha Shlemov"
description = "Math, code, AI compression."
default_language = "en"
output_dir = "public"
compile_sass = true
generate_feeds = true
feed_filenames = ["atom.xml"]
build_search_index = false

[markdown]

[extra]
author = "Sasha Shlemov"

[[taxonomies]]
name = "tags"
feed = true
